[files]
extend-exclude = [
    ".git/",
    "docs/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "Patrick Collison",
    "Copyright 2014 Unknwon",
    "[0-9A-Za-z/+=]{64}",
    "ZXJuZXQxDjAMBgNVBA-some-junk-Q4wDAYDVQQLEwVNaW5pbzEOMAwGA1UEAxMF",
    "eyJmb28iOiJiYXIifQ",
    'http\.Header\{"X-Amz-Server-Side-Encryptio":',
    'sessionToken',
]

[default.extend-words]
"encrypter" = "encrypter"
"requestor" = "requestor"

[default.extend-identifiers]
"bui" = "bui"
"toi" = "toi"
"ot" = "ot"
"dm2nd" = "dm2nd"
"HashiCorp" = "HashiCorp"
"ParseND" = "ParseND"
"ParseNDStream" = "ParseNDStream"
"TestGetPartialObjectMisAligned" = "TestGetPartialObjectMisAligned"
